### ISSUE TITLE
Drop orphaned package {gtools} as a dependency

### ISSUE THREAD

**Issue by kelly-sovacool** [talgalili/gplots#11]
The `gtools` packages has been orphaned, causing `gplots` and all packages that depend on it to fail R CMD check. 

```
* checking package dependencies ... WARNING
  Requires orphaned package: ‘gtools’
```

You can see this warning in CRAN's daily check: https://cran.r-project.org/web/checks/check_results_gplots.html

**Comment by talgalili** [comment]
Thanks.
It has been taken over by a new owner, and should return to CRAN soon.
Regardless, of removing the dependancy is easy, feel free to suggest a PR
and I'll review it.

WDYT?

**Comment by kelly-sovacool** [comment]
I haven't imported code from other packages before. If you link to an example of where you've done this, especially to make sure the original source is properly attributed, I can help with that.

**Comment by talgalili** [comment]
Hey @kelly-sovacool 
I took a look at these 3 functions.
`invalid` and `odd` seems like small functions that could have been just copy-pasted into the package.
```
> invalid
function (x) 
{
    if (missing(x) || is.null(x) || length(x) == 0) 
        return(TRUE)
    if (is.list(x)) 
        return(all(sapply(x, invalid)))
    else if (is.vector(x)) 
        return(all(is.na(x)))
    else return(FALSE)
}
<bytecode: 0x5571c1a25090>
<environment: namespace:gtools>
> odd
function (x) 
x%%2 == 1
<bytecode: 0x5571c1a304c0>
<environment: namespace:gtools>
```

The problem is in `mixedsort`, calls `mixedorder` which is a large function. In the current situation I think it is better to keep the dependency, given that the `gtools` package is supposed to be maintained.
Let's give it a week? If the gtools doesn't return, we can deal with mixedsort and mixedorder.

WDY?T

**Comment by kelly-sovacool** [comment]
`gtools` is no longer orphaned (https://github.com/r-gregmisc/gtools/issues/15). Thank you @bbolker!
